- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
    - name: disbale default nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enable default nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: downloade catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: extract catalogue
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue service to system directories
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: systemctl daemon-reload
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: copy mongodb client
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check products loaded or not
      ansible.builtin.command: mongosh --host mongo.blackweb.agency --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue catalogue output
      ansible.builtin.debug:
        msg: "{{catalogue_output}}"

    - name: load products
      ansible.builtin.shell: mongosh --host mongo.blackweb.agency < /app/db/master-data.js
      when: catalogue_output.stdout | int < 0
      


 
